### ISSUE TITLE
No constraint on 'infolocs' columns

### ISSUE THREAD

**Issue by basille** [ClementCalenge/adehabitatLT#1]
The function `infolocs` does not make any check on consistency on the columns of the `data.frame`s provided, beyond checking the `row.names`. This means that any mix of data can be provided as 'infolocs', as long as it has the correct row names. Here is a silly example that illustrates this clearly:

```
library(adehabitatLT)
data(puechcirc)
infolocs(puechcirc)
```

Returns `NULL`, there is no 'infolocs' yet. Let's give it a list of 3 data frames with a single column with different names and classes:

```
infolocs(puechcirc) <- list(
    data.frame(bla = 1:80, row.names = row.names(puechcirc[[1]])),
    data.frame(bli = 1:69, row.names = row.names(puechcirc[[2]])),
    data.frame(blop = as.character(1:66), row.names = row.names(puechcirc[[3]])))
puechcirc
```

Now the `ltraj` is said to have only `bla` as 'infolocs', given that the names are checked on the first burst. If we try to retrieve it:

```
infolocs(puechcirc)

[[1]]
   bla
1    1
2    2
3    3
…
79  79
80  80

[[2]]
data frame with 0 columns and 69 rows

[[3]]
data frame with 0 columns and 66 rows
```

It returns the column `bla` (i.e. the existing 'infolocs' column in the first burst) for each burst, which is an empty data frame for the second and third burst as `bla` does not exist here. Other functions simply fail, such as `ld`:

```
ld(puechcirc)

Error in data.frame(tr, id = iidd, burst = bur, do.call("rbind", inf)) : 
  arguments imply differing number of rows: 215, 80
```

I think `infolocs` should enforce the structure of each `data.frame` to be identical (same name, same class).

**Comment by ClementCalenge** [comment]
Solved in commit 87b55706ec

**Comment by basille** [comment]
What about enforcing same class too?

**Comment by ClementCalenge** [comment]
You are right, I change it immediately.

**Comment by ClementCalenge** [comment]
Done!
